### ISSUE TITLE
Using getResource instead of getResourceAsStream will cause issues with jars

### ISSUE THREAD

**Issue by sokratis12GR** [Discord4J/example-projects#1]
Problematic Line: [GlobalCommandRegistrar.java#106](https://github.com/Discord4J/example-projects/blob/master/gradle-simple-bot/src/main/java/com/novamaday/d4j/gradle/simplebot/GlobalCommandRegistrar.java#L106)

```
      URL url = GlobalCommandRegistrar.class.getClassLoader().getResource(commandsFolderName);
```

**Comment by NovaFox161** [comment]
What is the issue it causes? I tested this myself with a fully built jar and everything was working.

**Comment by sokratis12GR** [comment]
Previously it would print an unauthorized access exception for the resources directory while attempting to access it.
On a newer trial, it seems to be functional.

**Comment by NovaFox161** [comment]
Huh, well, if it crops back up reopen this and I'll take a further look at it

**Comment by sokratis12GR** [comment]
Not sure if worth reopening (but after catching the error stacktrace from the try catch in the main method)
![image](https://user-images.githubusercontent.com/12274096/136709413-7e30bdc5-26d4-4278-b0dc-854cb78ba5ed.png)
![image](https://user-images.githubusercontent.com/12274096/136709420-2ea4c14c-5298-4d69-9f24-1d011bc9157e.png)
![image](https://user-images.githubusercontent.com/12274096/136709423-4c058cf6-bd42-493d-850b-ca87b8c6158c.png)
![image](https://user-images.githubusercontent.com/12274096/136709429-ce8ce2e7-d137-435b-b8c7-6b6af06b9238.png)

**Comment by influnt** [comment]
> 
> 
> Not sure if worth reopening (but after catching the error stacktrace from the try catch in the main method) ![image](https://user-images.githubusercontent.com/12274096/136709413-7e30bdc5-26d4-4278-b0dc-854cb78ba5ed.png) ![image](https://user-images.githubusercontent.com/12274096/136709420-2ea4c14c-5298-4d69-9f24-1d011bc9157e.png) ![image](https://user-images.githubusercontent.com/12274096/136709423-4c058cf6-bd42-493d-850b-ca87b8c6158c.png) ![image](https://user-images.githubusercontent.com/12274096/136709429-ce8ce2e7-d137-435b-b8c7-6b6af06b9238.png)

I got the same error with jar on Windows & Ubuntu. 
Are there any solutions?

**Comment by VicenteRD** [comment]
```
    private static List<String> getCommandsJson() throws IOException {
        //The name of the folder the commands json is in, inside our resources folder
        final String commandsFolderName = "commands/";

        //Get the folder as a resource
        URL url = Util.getResource(commandsFolderName);
        Objects.requireNonNull(url, commandsFolderName + " could not be found");

        List<String> list = new ArrayList<>();

        try (
                InputStream inputStream = GlobalCommandRegistrar.class.getClassLoader()
                        .getResourceAsStream(commandsFolderName);
                BufferedReader reader = new BufferedReader(new InputStreamReader(inputStream))
        ) {
            String file;
            while ((file = reader.readLine()) != null) {
                String resourceFileAsString = getResourceFileAsString(commandsFolderName + file);
                list.add(resourceFileAsString);
            }
        }

        return list;
    }
```
Works :) Though it probably needs a `catch` and other safety checks
